toolbar = nuke.toolbar("Nodes")
m = toolbar.addMenu("MatteHue", icon="MatteHue.png")
m.addCommand("Voxel/V_Average",           "nuke.createNode('V_Average.gizmo')",   icon="V_Average.png")
m.addCommand("Voxel/V_Erode",             "nuke.createNode('V_Erode.gizmo')",     icon="V_Erode.png")
m.addCommand("Voxel/V_Grid",              "nuke.createNode('V_Grid.gizmo')",      icon="V_Grid.png")
m.addCommand("Voxel/V_Light Directional", "nuke.createNode('V_DirLight.gizmo')",  icon="V_DirLight.png")
m.addCommand("Voxel/V_Light Environment", "nuke.createNode('V_EnvLight.gizmo')",  icon="V_EnvLight.png")
m.addCommand("Voxel/V_Light Point",       "nuke.createNode('V_PtLight.gizmo')",   icon="V_PtLight.png")
m.addCommand("Voxel/V_Noise",             "nuke.createNode('V_Noise.gizmo')",     icon="V_Noise.png")
m.addCommand("Voxel/V_Preview",           "nuke.createNode('V_Preview.gizmo')",   icon="V_Preview.png")
m.addCommand("Voxel/V_Render",            "nuke.createNode('V_Render.gizmo')",    icon="V_Render.png")
m.addCommand("Voxel/V_Shape",             "nuke.createNode('V_Shape.gizmo')",     icon="V_Shape.png")
m.addCommand("Voxel/V_Transform",         "nuke.createNode('V_Transform.gizmo')", icon="V_Transform.png")